import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ClerkProvider, SignIn, SignedIn, SignedOut } from "@clerk/nextjs";
import "./globals.css";
import Sidebar from "@/components/commons/Sidebar";
import Header from "@/components/commons/Header";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <meta charSet="UTF-8" />
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
          />
          <link
            rel="icon"
            href="/favicon-digitalhub.png.webp"
          />
          <title>Digital Hub</title>
        </head>

        <body>
          <div className="flex items-center justify-center min-h-screen w-100">
            <SignedOut>
              <SignIn routing="hash" />
            </SignedOut>

            <SignedIn>
              <div
                className="flex flex-row w-full h-full"
                style={{ height: "100vh" }}
              >
                <Sidebar />
                <div className="flex flex-col w-full h-full">
                  <Header />
                  <main
                    className="flex flex-col w-full h-full p-8 border-t-2 border-gray-300 main-body"
                    style={{ height: "calc(100vh - 5rem)" }}
                  >
                    {children}
                  </main>
                </div>
              </div>
            </SignedIn>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
