import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import {
  ClerkProvider,
  SignIn,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
  
} from "@clerk/nextjs";
import "./globals.css";
import Sidebar from "@/components/commons/Sidebar";
import Header from "@/components/commons/Header";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          {/* <header>
           
          </header> */}
          <div className="flex items-center justify-center min-h-screen w-100">
            <SignedOut>
              <SignIn routing="hash" />
            </SignedOut>

            {/* <UserButton showName /> */}
            <SignedIn>
              <div
                className="flex flex-row w-full h-full"
                style={{ height: "100vh" }}
              >
                <Sidebar />
                <div className="flex flex-col w-full h-full">
                  <Header />
                  <main
                    className="flex flex-col w-full h-full p-8 border-t-2 border-gray-300"
                    style={{ height: "calc(100vh - 5rem)" }}
                  >
                  {children}

                  </main>
                </div>
              </div>
            </SignedIn>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
